# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meradio', '0002_auto_20161120_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pause_duration',
            field=models.FloatField(default='0'),
        ),
    ]
